create table if not exists public.mp_payments (
  id bigint generated by default as identity primary key,
  payment_id text unique not null,
  user_id uuid not null,
  plan_id text not null,
  status text not null,
  amount numeric,
  currency_id text,
  metadata jsonb,
  created_at timestamptz not null default now()
);

alter table public.mp_payments enable row level security;
